# Server configurations
server:
  host: "localhost"
  port: 8080

database:
  driver: "mysql"
  host: "your_db_host"
  port: 3306
  user: "your_db_user"
  password: "your_db_password"
  name: "your_db_name"